name: chessenv
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py39hc99e966_0
  - ca-certificates=2024.12.31=haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - numexpr=2.10.1=py39h4cd664f_0
  - numpy=2.0.2=py39h055cbcc_0
  - numpy-base=2.0.2=py39h65a83cf_0
  - openssl=3.0.15=h827c3e9_0
  - pandas=2.2.3=py39h5da7b33_0
  - pip=25.0=py39haa95532_0
  - python=3.9.21=h8205438_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py39haa95532_0
  - setuptools=72.1.0=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tzdata=2025a=h04d1e81_0
  - vc=14.42=haa95532_4
  - vs2015_runtime=14.42.34433=he0abc0d_4
  - wheel=0.45.1=py39haa95532_0
  - pip:
      - antlr4-python3-runtime==4.9.3
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - packaging==24.2
      - pyyaml==6.0.2
prefix: C:\Users\haoyan\anaconda3\envs\chessenv
